In [8]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [9]:
# File paths
genotype_file = r"C:\Users\Sandesh\Project\NMIMS Hackathon\gene.csv"
phenotype_file = r"C:\Users\Sandesh\Project\NMIMS Hackathon\phenotype.csv"
# Load the datasets
genotype_data = pd.read_csv(genotype_file)
phenotype_data = pd.read_csv(phenotype_file)

In [10]:
genotype_data

X1        X2        X3        X4        X5        X6        X7  \
0  -0.560476  0.253319 -0.710407  0.787739  2.198810 -0.375603 -0.715242   
1  -0.230177 -0.028547  0.256884  0.769042  1.312413 -0.561876 -0.752689   
2   1.558708 -0.042870 -0.246692  0.332203 -0.265145 -0.343917 -0.938539   
3   0.070508  1.368602 -0.347543 -1.008377  0.543194  0.090497 -1.052513   
4   0.129288 -0.225771 -0.951619 -0.119453 -0.414340  1.598509 -0.437160   
5   1.715065  1.516471 -0.045028 -0.280395 -0.476247 -0.088565  0.331179   
6   0.460916 -1.548753 -0.784904  0.562990 -0.788603  1.080799 -2.014210   
7  -1.265061  0.584614 -1.667942 -0.372439 -0.594617  0.630754  0.211980   
8  -0.686853  0.123854 -0.380227  0.976973  1.650907 -0.113640  1.236675   
9  -0.445662  0.215942  0.918997 -0.374581 -0.054028 -1.532902  2.037574   
10  1.224082  0.379639 -0.575347  1.052711  0.119245 -0.521117  1.301176   
11  0.359814 -0.502323  0.607964 -1.049177  0.243687 -0.489870  0.756775   
12  0.400771 -0.333207 -1.617883 -1.260155  1.232476  0.047154 -1.726730   
13  0.110683 -1.018575 -0.055562  3.241040 -0.516064  1.300199 -0.601507   
14 -0.555841 -1.071791  0.519407 -0.416858 -0.992507  2.293079 -0.352046   
15  1.786913  0.303529  0.301153  0.298228  1.675697  1.547581  0.703524   
16  0.497850  0.448210  0.105676  0.636570 -0.441163 -0.133151 -0.105671   
17 -1.966617  0.053004 -0.640706 -0.483781 -0.723066 -1.756527 -1.258649   
18  0.701356  0.922267 -0.849704  0.516862 -1.236273 -0.388780  1.684436   
19 -0.472791  2.050085 -1.024129  0.368965 -1.284716  0.089207  0.911391   
20 -1.067824 -0.491031  0.117647 -0.215381 -0.573973  0.845013  0.237430   
21 -0.217975 -2.309169 -0.947475  0.065293  0.617986  0.962528  1.218109   
22 -1.026004  1.005739 -0.490557 -0.034067  1.109848  0.684309 -1.338774   
23 -0.728891 -0.709201 -0.256092  2.128452  0.707588 -1.395274  0.660820   
24 -0.625039 -0.688009  1.843862 -0.741336 -0.363657  0.849643 -0.522912   
25 -1.686693  1.025571 -0.651950 -1.095996  0.059750 -0.446557  0.683746   
26  0.837787 -0.284773  0.235387  0.037788 -0.704596  0.174803 -0.060822   
27  0.153373 -1.220718  0.077961  0.310481 -0.717218  0.074551  0.632961   
28 -1.138137  0.181303 -0.961857  0.436523  0.884650  0.428167  1.335518   
29  1.253815 -0.138891 -0.071308 -0.458365 -1.015593  0.024675  0.007290   
30  0.426464  0.005764  1.444551 -1.063326  1.955294 -1.667475  1.017559   
31 -0.295071  0.385280  0.451504  1.263185 -0.090320  0.736496 -1.188434   
32  0.895126 -0.370660  0.041233 -0.349650  0.214539  0.386027 -0.721604   
33  0.878133  0.644377 -0.422497 -0.865513 -0.738528 -0.265652  1.519218   
34  0.821581 -0.220487 -2.053247 -0.236280 -0.574389  0.118145  0.377388   
35  0.688640  0.331782  1.131337 -0.197176 -1.317016  0.134039 -2.052223   
36  0.553918  1.096839 -1.460640  1.109920 -0.182925  0.221019 -1.364037   
37 -0.061912  0.435181  0.739948  0.084737  0.418982  1.640846 -0.200781   
38 -0.305963 -0.325932  1.909104  0.754054  0.324304 -0.219050  0.865779   
39 -0.380471  1.148808 -1.443893 -0.499292 -0.781536  0.168065 -0.101883   
40 -0.694707  0.993504  0.701784  0.214445 -0.788622  1.168384  0.624187   
41 -0.207917  0.548397 -0.262197 -0.324686 -0.502199  1.054181  0.959005   
42 -1.265396  0.238732 -1.572144  0.094584  1.496061  1.145263  1.671055   
43  2.168956 -0.627906 -1.514668 -0.895363 -1.137304 -0.577468  0.056017   
44  1.207962  1.360652 -1.601536 -1.310802 -0.179052  2.002483 -0.051982   
45 -1.123109 -0.600260 -0.530907  1.997213  1.902362  0.066701 -1.753237   
46 -0.402885  2.187333 -1.461756  0.600709 -0.100975  1.866852  0.099328   
47 -0.466655  1.532611  0.687917 -1.251271 -1.359841 -1.350903 -0.571850   
48  0.779965 -0.235700  2.100109 -0.611166 -0.664769  0.020984 -0.974010   
49 -0.083369 -1.026421 -1.287030 -1.185480  0.485460  1.249915 -0.179906   

          X8        X9       X10  ...     X1991     X1992     X1993     X1994  \
0   1.014943 -0.073556  1.430402  ... -0.977420  0.1

In [11]:
phenotype_data

V1
0  -311.097535
1   -68.479413
2   289.721130
3  -435.731604
4    46.893067
5   -27.363154
6   474.878695
7  -367.406108
8  -213.329640
9   -98.646458
10  171.667784
11   54.813010
12 -203.330103
13  594.418864
14  213.149659
15   84.497655
16   98.135194
17 -313.334123
18   53.821137
19 -366.795418
20  -19.600432
21  327.477757
22 -494.831610
23  161.923809
24   97.829880
25 -607.852661
26  269.460835
27  370.867097
28 -299.064432
29  267.359670
30 -165.657815
31   36.000748
32  153.880004
33  -31.139430
34   98.492145
35  206.666416
36  -81.103033
37  -91.615986
38  159.180627
39 -330.821472
40 -167.848563
41 -136.966191
42 -456.327038
43  399.269583
44 -285.266664
45  -65.571931
46 -501.047262
47 -331.626516
48  276.836481
49  -36.966083

In [12]:
# Standardize the genotype and phenotype datasets

scaler_genotype = StandardScaler()
scaler_genotype

StandardScaler()

In [13]:
scaler_phenotype = StandardScaler()
scaler_phenotype

StandardScaler()

In [14]:
genotype_scaled = scaler_genotype.fit_transform(genotype_data)
pd.DataFrame(genotype_scaled)

0         1         2         3         4         5         6     \
0  -0.649031  0.119273 -0.466112  0.812627  2.353556 -0.668738 -0.702485   
1  -0.288666 -0.195187  0.521533  0.792340  1.408439 -0.868031 -0.739158   
2   1.663063 -0.211167  0.007360  0.318348 -0.273625 -0.634838 -0.921171   
3   0.039391  1.363528 -0.095613 -1.136244  0.588263 -0.170063 -1.032792   
4   0.103522 -0.415218 -0.712400 -0.171719 -0.432703  1.443343 -0.430144   
5   1.833653  1.528495  0.213268 -0.346350 -0.498711 -0.361640  0.322329   
6   0.465338 -1.891188 -0.542178  0.568763 -0.831759  0.889451 -1.974631   
7  -1.417756  0.488879 -1.443797 -0.446221 -0.624923  0.407953  0.205592   
8  -0.786913 -0.025162 -0.128984  1.017956  1.769357 -0.388467  1.209127   
9  -0.523766  0.077574  1.197578 -0.448545 -0.048522 -1.906921  1.993489   
10  1.297975  0.260202 -0.328211  1.100135  0.136230 -0.824423  1.272296   
11  0.355033 -0.723751  0.880001 -1.180515  0.268916 -0.790992  0.739137   
12  0.399719 -0.535078 -1.392685 -1.409436  1.323206 -0.216435 -1.693087   
13  0.083223 -1.299702  0.202512  3.474577 -0.541166  1.124184 -0.591098   
14 -0.643975 -1.359071  0.789580 -0.494418 -1.049171  2.186457 -0.346789   
15  1.912042  0.175290  0.566734  0.281484  1.795789  1.388856  0.686985   
16  0.505635  0.336702  0.367143  0.648601 -0.461303 -0.409342 -0.105501   
17 -2.183175 -0.104205 -0.394945 -0.567032 -0.761881 -2.146175 -1.234671   
18  0.727665  0.865579 -0.608341  0.518713 -1.309085 -0.682836  1.647642   
19 -0.553365  2.123816 -0.786436  0.358237 -1.360737 -0.171443  0.890560   
20 -1.202564 -0.711153  0.379366 -0.275805 -0.602911  0.637186  0.230516   
21 -0.275353 -2.739539 -0.708169  0.028739  0.668009  0.762914  1.190944   
22 -1.156938  0.958703 -0.241637 -0.079072  1.192455  0.465251 -1.313142   
23 -0.832778 -0.954551 -0.002238  2.267365  0.763548 -1.759674  0.645163   
24 -0.719472 -0.930908  2.141906 -0.846493 -0.378663  0.642140 -0.514127   
25 -1.877769  0.980829 -0.406426 -1.231316  0.072793 -0.744652  0.667615   
26  0.876516 -0.481043  0.499583 -0.001105 -0.742188 -0.079865 -0.061578   
27  0.129799 -1.525220  0.338845  0.294779 -0.755645 -0.187123  0.617879   
28 -1.279278  0.038930 -0.722854  0.431542  0.952339  0.191206  1.305929   
29  1.330415 -0.318291  0.186435 -0.539456 -1.073786 -0.240485  0.005128   
30  0.427750 -0.156908  1.734192 -1.195867  2.093908 -2.050899  0.994535   
31 -0.359467  0.266495  0.720248  1.328509 -0.087218  0.521085 -1.165906   
32  0.939074 -0.576862  0.301344 -0.421495  0.237836  0.146121 -0.708716   
33  0.920535  0.555553 -0.172144 -0.981230 -0.778367 -0.551103  1.485836   
34  0.858835 -0.409322 -1.837211 -0.298482 -0.603354 -0.140483  0.367584   
35  0.713792  0.206810  1.414387 -0.256053 -1.395177 -0.123478 -2.011858   
36  0.566806  1.060338 -1.232133  1.162209 -0.185958 -0.030418 -1.337883   
37 -0.105083  0.322167  1.014762  0.049837  0.455823  1.488640 -0.198647   
38 -0.371350 -0.526961  2.208520  0.776077  0.354873 -0.501245  0.845890   
39 -0.452641  1.118316 -1.215034 -0.583863 -0.824225 -0.087073 -0.101791   
40 -0.795482  0.945053  0.975795  0.190576 -0.831779  0.983157  0.609287   
41 -0.264379  0.448474 -0.008472 -0.394407 -0.526382  0.860973  0.937191   
42 -1.418122  0.103000 -1.345984  0.060520  1.604252  0.958420  1.634538   
43  2.328862 -0.863856 -1.287298 -1.013619 -1.203560 -0.884712  0.052848   
44  1.280388  1.354659 -1.375994 -1.464390 -0.181828  1.875551 -0.052920   
45 -1.262881 -0.833012 -0.282835  2.124965  2.037469 -0.195522 -1.719047   
46 -0.477095  2.276936 -1.233272  0.609691 -0.098579  1.730441  0.095265   
47 -0.546671  1.546502  0.961636 -1.399797 -1.440839 -1.712202 -0.562054   
48  0.813431 -0.426295  2.403545 -0.705252 -0.699722 -0.244435 -0.955909   
49 -0.128494 -1.308454 -1.054870 -1.328410  0.526704  1.070386 -0.178203   

        7         8         9     ...      1990      1991      1992      1993  \
0   1.043015 -0.007820  1.254122  ... -0.903621  0

In [15]:
phenotype_scaled = scaler_phenotype.fit_transform(phenotype_data)
phenotype_final = pd.DataFrame(phenotype_scaled)
phenotype_final

# phenotype_final.to_csv('phenotype_final.csv')

0
0  -1.013440
1  -0.132362
2   1.168459
3  -1.466054
4   0.286618
5   0.016954
6   1.840866
7  -1.217927
8  -0.658392
9  -0.241915
10  0.739743
11  0.315380
12 -0.622078
13  2.274981
14  0.890386
15  0.423181
16  0.472706
17 -1.021562
18  0.311778
19 -1.215709
20  0.045144
21  1.305573
22 -1.680678
23  0.704357
24  0.471597
25 -2.091119
26  1.094883
27  1.463144
28 -0.969741
29  1.087252
30 -0.485269
31  0.247062
32  0.675146
33  0.003240
34  0.474002
35  0.866842
36 -0.178205
37 -0.216383
38  0.694395
39 -1.085068
40 -0.493225
41 -0.381074
42 -1.540847
43  1.566289
44 -0.919634
45 -0.121803
46 -1.703250
47 -1.087992
48  1.121668
49 -0.017920

In [16]:
# correlation of each gene with the phenotype

correlations = np.corrcoef(genotype_scaled.T, phenotype_scaled.flatten())
correlations

array([[ 1.        , -0.03586983,  0.02910612, ..., -0.01351599,
        -0.19591443,  0.56003235],
       [-0.03586983,  1.        , -0.15607113, ...,  0.02957629,
         0.13286071, -0.70573254],
       [ 0.02910612, -0.15607113,  1.        , ..., -0.09947458,
        -0.13475165,  0.30507828],
       ...,
       [-0.01351599,  0.02957629, -0.09947458, ...,  1.        ,
         0.18162734, -0.05906886],
       [-0.19591443,  0.13286071, -0.13475165, ...,  0.18162734,
         1.        , -0.15239851],
       [ 0.56003235, -0.70573254,  0.30507828, ..., -0.05906886,
        -0.15239851,  1.        ]])

In [17]:
correlations = np.corrcoef(genotype_scaled.T, phenotype_scaled.flatten())[:2000, 2000]
print(correlations)
len(correlations)

[ 0.56003235 -0.70573254  0.30507828 ... -0.00144403 -0.05906886
 -0.15239851]


2000

In [18]:
np.sort(np.abs(correlations))[-200:]

array([0.23959014, 0.24058194, 0.24093341, 0.24149103, 0.24149179,
       0.24205378, 0.2422092 , 0.24246178, 0.24313701, 0.24384198,
       0.24499459, 0.24503702, 0.24527332, 0.24528027, 0.24540038,
       0.24598926, 0.24606098, 0.24606275, 0.24645162, 0.24660398,
       0.24661855, 0.24763379, 0.24816812, 0.24914928, 0.24985444,
       0.24993362, 0.24999375, 0.25039969, 0.25063287, 0.2506486 ,
       0.25069791, 0.25234554, 0.25271746, 0.25309281, 0.25312913,
       0.25441757, 0.25463385, 0.25564175, 0.25568837, 0.25572855,
       0.25675498, 0.25696286, 0.25771622, 0.25817303, 0.25820175,
       0.2587374 , 0.25879426, 0.25989748, 0.26106639, 0.26183318,
       0.26183491, 0.26197396, 0.26211877, 0.26259148, 0.26267495,
       0.26271406, 0.26292526, 0.26308143, 0.26320551, 0.26380254,
       0.26450749, 0.26455355, 0.26508169, 0.26552178, 0.26580418,
       0.26589481, 0.26738551, 0.26849898, 0.26851225, 0.2689409 ,
       0.26938395, 0.27004195, 0.27076891, 0.27079191, 0.27154

In [22]:
# 200 genes based on absolute correlation

top_gene = np.argsort(np.abs(correlations))[-5:]
top_gene

array([272, 141, 429,   0,   1], dtype=int64)

In [21]:
top_gene

array([ 568,  303, 1098, 1766, 1132,  936, 1242,  740, 1307,  199, 1201,
        307,  461,  368, 1590, 1454,  558,  811, 1249, 1799,   15, 1804,
       1729,  175,  505,  596,  977,  888,  662, 1697, 1696,  761, 1156,
        249,  641,  471, 1480,  359, 1315, 1962,  212,  794,  713,  240,
        712, 1919,  877, 1881,  784, 1679,  785, 1609, 1569, 1732,  238,
       1435, 1809,  615,   56, 1627,  929, 1208, 1888,  989,  271,  880,
       1777,  226, 1265, 1988,  930, 1538, 1794, 1187,  829,  702,  574,
       1313, 1303, 1194,  133, 1876, 1091, 1765, 1819, 1789, 1123, 1535,
       1263, 1088,  251, 1469, 1976,  511,   22, 1365, 1043,  872, 1870,
       1622, 1670,  227, 1571, 1527, 1703,  921,   88, 1908, 1066, 1227,
       1025, 1404, 1258, 1243,  152,  298,  122, 1376, 1744, 1311,  490,
       1031, 1433,  462, 1638, 1996,    4,  252, 1665,    2,  447,  354,
        435, 1236,  412,    3, 1102, 1317, 1633, 1436, 1903, 1210,  898,
        862,  232,  925, 1561,  567,   78, 1381,  5

In [89]:
# Extract the selected genes and forming of new dataframe

genotype_final = genotype_scaled[:, top_gene_indices]
genotype_final = pd.DataFrame(genotype_final,columns=[f"X{i+1}" for i in top_gene_indices])
genotype_final

# genotype_final.to_csv('Dataset.csv')

In [72]:
# shape of the reduced dataset

print("Shape of the reduced genotype dataset:", genotype_final.shape)

print("\nIndices of the top 200 genes:\n", top_gene_indices)

Shape of the reduced genotype dataset: (50, 200)

Indices of the top 200 genes:
 [ 568  303 1098 1766 1132  936 1242  740 1307  199 1201  307  461  368
 1590 1454  558  811 1249 1799   15 1804 1729  175  505  596  977  888
  662 1697 1696  761 1156  249  641  471 1480  359 1315 1962  212  794
  713  240  712 1919  877 1881  784 1679  785 1609 1569 1732  238 1435
 1809  615   56 1627  929 1208 1888  989  271  880 1777  226 1265 1988
  930 1538 1794 1187  829  702  574 1313 1303 1194  133 1876 1091 1765
 1819 1789 1123 1535 1263 1088  251 1469 1976  511   22 1365 1043  872
 1870 1622 1670  227 1571 1527 1703  921   88 1908 1066 1227 1025 1404
 1258 1243  152  298  122 1376 1744 1311  490 1031 1433  462 1638 1996
    4  252 1665    2  447  354  435 1236  412    3 1102 1317 1633 1436
 1903 1210  898  862  232  925 1561  567   78 1381  560  489 1737  280
 1247  270  304 1887 1495 1419 1637  917 1599 1613  756  496 1134 1740
 1086  826  563  781 1904 1556  139 1406 1021 1045 1716 1504 1306  